<?php

use Drupal\Core\Link;
use Drupal\node\Entity\Node;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implement hook_entity_load
 * Check for translations of AT descriptions and notify users
 * @param array $entities
 * @param $entity_type_id
 */
function buddy_entity_load(array $entities, $entity_type_id) {
  if ($entity_type_id == 'node' && count($entities) == 1) {
    $node = array_values($entities)[0];
    if ($node->getType() == 'at_description') {
      $node_lang = $node->get('field_at_description_language')->getString();
      $user_lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
      if (!empty($node_lang) && !empty($user_lang) && $node_lang !== $user_lang) {
        // Fetch AT entry of AT description
        $query = \Drupal::entityQuery('node')
          ->condition('type', 'at_entry')
          ->condition('field_at_descriptions', $node->id(), 'IN');
        $results = $query->execute();
        if (empty($results)) {
          return;
        }
        // Find AT description in user's language
        $query = \Drupal::entityQuery('node')
          ->condition('type', 'at_description')
          ->condition('field_at_entry', array_shift($results))
          ->condition('field_at_description_language', $user_lang)
          ->condition('status', 1);
        $results = $query->execute();
        if (!empty($results)) {
          $messenger = \Drupal::messenger();
          $languages = \Drupal::service('language_manager')->getStandardLanguageList();
          $messenger->addMessage(
            t('This entry is available in @language: @at_link.',
              [ '@language' => $languages[$user_lang][0],
                '@at_link' => Link::createFromRoute(
                  t('click here to see it'),
                  'entity.node.canonical', ['node' => array_shift($results)])
                  ->toString(),]),
            $messenger::TYPE_STATUS,
            FALSE);
        }
      }
    }
  }
}


/**
 * Implements hook_user_login().
 */

function buddy_user_login($account) {


  $current_route = Drupal::routeMatch()->getRouteName();
  $request = Drupal::request();
  if ($request->getRequestFormat() !== 'html') {
    return;
  }
  $destination = $request->query->get('destination');
  if ($destination && $destination != '/user/login') {
    return;
  }

  $middleware = \Drupal::service('http_middleware.buddy');

  //Accessing the site in maintenance mode.
  if (\Drupal::state()
      ->get('system.maintenance_mode') && !$account->hasPermission('access site in maintenance mode')) {
    // The site is in maintenance mode and the user is not allowed in.
    // Step out and let Drupal handle it.
    $homeResponse = new RedirectResponse(URL::fromUserInput('/')->toString());
    $middleware->setRedirectResponse($homeResponse);

  }


  if (!in_array($current_route, ['user.reset', 'user.reset.login'])) {

    if( !in_array("at_moderator", $account->getRoles()) &&!in_array("administrator", $account->getRoles())){

      $user = \Drupal::currentUser();
      $user_profileID = \Drupal::entityQuery('node')
        ->condition('type', 'user_profile')
        ->condition('uid', $user->id(), '=')
        ->condition('field_user_profile_finished', true, '=')
        ->execute();


      if(count($user_profileID) == 0){
        $redirectResponse = new RedirectResponse(URL::fromRoute('buddy.user_profile')->toString());
        $middleware->setRedirectResponse($redirectResponse);

      }else{
        $redirectResponse = new RedirectResponse(URL::fromRoute('buddy.user_overview')->toString());
        $middleware->setRedirectResponse($redirectResponse);

      }




    }



    return;

  }

}
